version: '3.9'

services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 30s
      timeout: 10s
      retries: 5
